# Generated by Django 5.0.1 on 2024-01-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("porkprosper", "0002_user_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(default="Descripcion", max_length=200),
        ),
    ]
